### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by wumail** [wbccb/visualization-study#1]
所以看起来「像素检测-基于随机颜色的检测」用来做元素选中测试是相对来说最高效的？印象中好几个canvas的图形库都是用的这种方式？

**Comment by wbccb** [comment]
各种方式的应用场景和性能对比我还没开始深入研究🤔️不过「像素检测-基于随机颜色的检测」在多个图形库的应用，我的理解是是它自身更加简单容易实现（相比较一些复杂算法而言）
